### PR TITLE
Some changes to StaxNavException

### PR DESCRIPTION
**Pull request by nscavell**
Mainly I would like it to display the location information in the message of the exception like XMLStreamException does.

I also added normal Exception constructors for times when Location is irrelevant.  Not sure how set you are on requiring the Location for this exception.  But in my code I just pass null for the location which is sort of ugly.

### CODE REVIEW

**Comment by vietj** [comment]
hum actually I did a constructor with Location, to force the developer (like you :-) ) to always provide a location. But maybe this is related to a read operation and you are doing XML write operation, is it correct ?

**Comment by nscavell** [comment]
That's correct.  I can change the exception I'm using for the writer stuff, no big deal.  I figured you wanted to force the location and I'm fine with that.  Printing out the location info is more of a need for me at this point.  Want me to remove those two constructors for now ?

**Comment by vietj** [comment]
no, it's fine, the first thought was that only reading would be done, but both can be provided

**Comment by nscavell** [comment]
Yea I really didn't want to add any writer specific stuff yet until you decided on what you wanted to do.  Reason I didn't add an additional method to the ValueType class which would be needed for writing.  Plus having StaxNavException on my writer looks strange at the moment.  Up to you...

**Pull request merged**
