### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by nscavell**
Allow null to be returned from next method when passing in set.
Added DATE and DATE_TIME value types.

### CODE REVIEW

**Comment by vietj** [comment]
Hi Nick,

I wanted to avoid null to be returned because of the switch use case :

switch (nav.next(allowed)) { }

when null is returned, java will throw an NPE.

what we could do instead is to specify a default element when not found so it would be like:

switch (nav.next(allowed), Element.UNKNOWN) { }

is it ok for you ?

**Comment by nscavell** [comment]
Hmm.  I was following more of the <code>N next()</code> method which can return null, since the method returns N for <code>next(Set<N> names)</code>.

Let me think about it because I did something similar in stax-builder, to pass in an enum value in case something wasn't found to avoid NPE on switch statement, but I also had an EnumElement interface that was to be implemented by all Enum types used in stax-builder that could define a getUnknown method.  This could be used in the Naming.getName method.  Let me create a branch and show you what I'm thinking.

Just as a note, I typically find myself doing a <code>while(nav.next() != null)</code> in order loop while parsing.  Maybe we need a hasNext() so I'm not forced to this.

**Comment by vietj** [comment]
yes, first I wanted to also return null, but the thing that prevented me to do it was the switch(null). If next() returns an enum then it makes sense to use it in a switch and the nullity prevents it's usability. The behavior could be:
1/ try to find a way to define a default enum value
2/ if no such default enum value exist, then throw an exception as it does now

about the hasNext(), yes it makes sense, so I believe you want to replace the following

while (nav.next() != null) { N name = nav.getName(); }

by

while (nav.hasNext()) { N name = nav.next(); }

right ?

**Comment by nscavell** [comment]
Correct. Question is should the hasNext() method just call the underlying stream reader hasNext() or should it look ahead and see if there's actually more content, aka another START_ELEMENT.

**Comment by nscavell** [comment]
Closing this one...

**Pull request closed without merging**
